<a href="https://colab.research.google.com/github/soloflare1/flare/blob/main/Nosratee_Jahan_Naba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Email address : itsaareebaa@gmail.com**

**0) Starter Code (Run First)**

In [42]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


## **1) NumPy **

Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.

In [5]:
age = np.array(ages)
salary = np.array(salaries)
print(age)
print(salary)
# age
print(age.dtype)
print(age.ndim)
print(age.shape)
print(age.size)

# salary
print(salary.dtype)
print(salary.ndim)
print(salary.shape)
print(salary.size)


[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10
int64
1
(10,)
10


Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [6]:
highest_salary = np.max(salaries)
lowest_salary = np.min(salaries)
avg_salary = np.average(salaries)

print(highest_salary)
print(lowest_salary)
print(avg_salary)

89735
30769
57446.9


Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [11]:
ages_greater_than_30 = ages[ages > 30]
print(ages_greater_than_30)

No_employees_are_older_than_30 = len(ages_greater_than_30)
print(No_employees_are_older_than_30)

[56 46 32 38 56 36 40]
7


Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [14]:
updated_ages = ages.copy()
updated_ages += 5

print(updated_ages)


[56 46 32 25 38 56 36 40 28 28]
[61 51 37 30 43 61 41 45 33 33]
[56 46 32 25 38 56 36 40 28 28]


Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

In [16]:
total_salary = np.sum(salaries)
print(total_salary)

highest_salary = np.max(salaries)
lowest_salary = np.min(salaries)

diff_between_high_low = highest_salary - lowest_salary
print(diff_between_high_low)

574469
58966


## **2) Pandas**

Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

In [45]:
# Load the employees.csv file into a Pandas DataFrame.
df = pd.read_csv('employees.csv')

#  Display the first 5 rows
print(df.head(5))

#  basic info
df.info()

# summary statistics
df.describe()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().

In [46]:
DF.loc[:, ['id', 'age', 'salary']]

id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

In [47]:
DF.tail(3)

id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR

Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

In [48]:
work_in_IT = DF.loc[DF['dept'] == 'IT']
work_in_IT

id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

In [50]:
total_IT_department = len(work_in_IT)

print(total_IT_department)

3


Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.

In [49]:
DF

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [51]:
copy = DF.sort_values(['salary'], ascending=False)
topper = copy.loc[:,['salary','dept','age']]
topper.head(3)

salary     dept  age
6   89735  Finance   36
7   86101       IT   40
0   77191       HR   56

Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.


In [53]:

DF.loc[DF['salary'] > 80000 ,'salary'] = 80000
# DF
avg_salary = DF['salary'].mean()

print(avg_salary)

55863.3
