In [ ]:
# Broadcasting = Auto-stretching arrays to match shapes.
# Works when:
# - Shapes match from the end
# - Or one shape is 1

# a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)  
# b = np.array([10, 20, 30])           # shape (3,)  
# print(a + b)


# a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
# b = np.array([10, 20])               # shape (2,)
# print(a + b)  # ❌ Error!

In [ ]:
import numpy as np 
x = np.array([10, 8, 4, 100])

res = x**2    # divide [ 2  2  2  2] then 10^2 8^2..
print(res)


res = x+2    # divide [ 2  2  2  2] then 10^2 8^2..
print(res)



matrix = np.array([
    [10, 8, 4, 100],
    [2,4, 5,5]])

res = matrix+2    # divide  2  2  2  2 
                #         2  2  2  2  then 
print(res)


# rulling = cols er size & vector er size same hote hobe
matrix = np.array([
    [10, 8, 4, 100],
    [2,4, 5,5]])

vector = np.array([1,2,3,4])
res = matrix + vector    
print(res)


[  100    64    16 10000]
[ 12  10   6 102]
[[ 12  10   6 102]
 [  4   6   7   7]]
[[ 11  10   7 104]
 [  3   6   8   9]]


In [ ]:
# So the operation looks like:

# [10,  8,  4, 100]   +   [1, 2, 3, 4]   =   [11, 10, 7, 104]
# [ 2,  4,  5,   5]   +   [1, 2, 3, 4]   =   [3, 6, 8, 9]
