In [ ]:

import numpy as np

a1 = np.array([1,2,3,4])
a2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

# view
a_mod = a1[1:4]
# a_mod is a view of a1 not copyright 
# so if we change it ,it will also change original aa1

print(a1)
print(a_mod)

a_mod[0] = 100
print(a1)

a1[1:4] = 0
print(a1)   #[1 0 0 0]

# copy
# no change in a1
a_mod = a1[1:4].copy()
a_mod[0] = 2
print(a1)



[1 2 3 4]
[2 3 4]
[  1 100   3   4]
[1 0 0 0]
[1 0 0 0]


In [20]:
# advanced indexing

lst = np.array([10,20,30,40,50,60,70])

val = lst[[2,3]]   #2 and 3 no index er value
print(val)

val = lst[[2,3,5,6]]   
print(val)

print(a2)
print()
print(a2[0,1], [1,3])

#  boolean kono kichu diye
print(a2[a2 > 2])

a2[a2>2] = 0
print(a2)

[30 40]
[30 40 60 70]
[[0 2 3 4]
 [5 6 7 8]]

2 [1, 3]
[3 4 5 6 7 8]
[[0 2 0 0]
 [0 0 0 0]]


In [23]:
a = np.array([[10,20], [100,200]])

# iteration
for i in a:
    for j in a:
        print(i,j)
        
        
for i in np.nditer(a):
    print(i)
    

[10 20] [10 20]
[10 20] [100 200]
[100 200] [10 20]
[100 200] [100 200]
10
20
100
200
