In [ ]:
# matrix for linear algebra

# diagonal matrix
import numpy as np
a = np.diag([1,2,3,4])
print(a)
print(a.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [11]:
# identity matrix

a = np.eye(4)
print(a)
print(a.shape)
print()

# np.eye(row, col)  3*3 identity rest 0
a = np.eye(3,5)
print(a)
print(a.shape)
print()

a = np.eye(3,5, -1)
print(a)
print(a.shape)
print()

a = np.eye(3,5, 1)
print(a)
print(a.shape)
print()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
(3, 5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(3, 5)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
(3, 5)

