In [2]:
import numpy as np 
x = np.array([10, 8, 4, 100])
y = np.array([5, 1, 7, 3])

print(x > y)
print(x == y)



# all () -> true kina
print(np.all(x==y))

# any () -> jekono 1ta true kina
print(np.any(x==y))

[ True  True False  True]
[False False False False]
False
False


## sorting

In [9]:
#  inplace (prev version can't find)
z = x.copy()
print(z)

z.sort()
print(z)



[ 10   8   4 100]
[  4   8  10 100]


In [7]:

# copy sorting

print(x)
y = np.sort(x)
print(y)
print(x)


[ 10   8   4 100]
[  4   8  10 100]
[ 10   8   4 100]


In [12]:
#  2d

mat = np.array([[10,3,5], [8,4,9]])
print(mat)

# horizontal axis = 1

hort_sort = np.sort(mat, axis=1)
print(hort_sort)

# horizontal axis = 1

vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[10  3  5]
 [ 8  4  9]]
[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## searching

In [13]:
print(x)

[ 10   8   4 100]


In [ ]:
#  np. where
#return index
index = np.where(x==8)
print(index)

index = np.where(x>8)
print(index)

(array([1]),)
(array([0, 3]),)


In [23]:
#  np. where(condition, x, y)  
print(mat)
index = np.where(mat>8)
print(index)


[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))


In [19]:
#  np. where(condition, x, y)  if true x, otherwise replace with y
index = np.where(x==8, x,0)  #return array
print(index)


[0 8 0 0]


In [ ]:
#  np. where(condition, x, y)  if true x, otherwise replace with y
index = np.where(mat==8, mat,0)  
print(index)

[[0 0 0]
 [8 0 0]]


## min , max

In [26]:
print(x)

# return index
mx_val =np.argmax(x)
print(mx_val)

x = np.array([100, 8, 4, 100])
mx_val =np.argmax(x)
print(mx_val) #first idx


mn_val =np.argmin(x)
print(mn_val)


[100   8   4 100]
0
0
2


In [30]:
a = np.random.randint(1,100,size=(100,))
print(a)

[40 32 45 71 77 72  2 95 82 74 86 86 99 93 60 82 54 46  5 11 59 26 94 97
 91 70 82 60 52 75 20 59 30 60 90 20 92 11 94 53 11 38 50 83 66 88 70 50
 66 52 60 56  2  6 66 78 23  2 13 20 99 13 13 54 69 39 44 69 22 55 72 29
 76 42 64 32 19 20 20  8 33 55  7 26 10 24 84  3 25 46 74 65 20 61 25 71
 63 14 21 44]


In [35]:
val_grat_than_60 = np.count_nonzero(a > 60)
print(val_grat_than_60)


39


In [32]:
unique_val = np.unique(a)
print(unique_val)

[ 2  3  5  6  7  8 10 11 13 14 19 20 21 22 23 24 25 26 29 30 32 33 38 39
 40 42 44 45 46 50 52 53 54 55 56 59 60 61 63 64 65 66 69 70 71 72 74 75
 76 77 78 82 83 84 86 88 90 91 92 93 94 95 97 99]


In [33]:
unique_val = np.unique(a, return_counts=True)
print(unique_val)

(array([ 2,  3,  5,  6,  7,  8, 10, 11, 13, 14, 19, 20, 21, 22, 23, 24, 25,
       26, 29, 30, 32, 33, 38, 39, 40, 42, 44, 45, 46, 50, 52, 53, 54, 55,
       56, 59, 60, 61, 63, 64, 65, 66, 69, 70, 71, 72, 74, 75, 76, 77, 78,
       82, 83, 84, 86, 88, 90, 91, 92, 93, 94, 95, 97, 99], dtype=int32), array([3, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 6, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 4, 1, 1, 1, 1, 3, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2]))


In [34]:
#  unpake
unique_val, count = np.unique(a, return_counts=True)
print(unique_val)
print(count)

[ 2  3  5  6  7  8 10 11 13 14 19 20 21 22 23 24 25 26 29 30 32 33 38 39
 40 42 44 45 46 50 52 53 54 55 56 59 60 61 63 64 65 66 69 70 71 72 74 75
 76 77 78 82 83 84 86 88 90 91 92 93 94 95 97 99]
[3 1 1 1 1 1 1 3 3 1 1 6 1 1 1 1 2 2 1 1 2 1 1 1 1 1 2 1 2 2 2 1 2 2 1 2 4
 1 1 1 1 3 2 2 2 2 2 1 1 1 1 3 1 1 2 1 1 1 1 1 2 1 1 2]


# Statistical function

In [38]:
#  data load
# genfromtxt - > for txt & csv file
data = np.genfromtxt('students_scores.csv', delimiter=',', skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [41]:
# statistics

math_marks = data[::, :1]
# print(math_marks) # col wise display
print(math_marks.T) # row wise display


[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]


In [46]:
max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

avg_math_marks = np.mean(math_marks)
print(avg_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# SD-> standard deviation avg er kachakachi kina?
std_math_marks = np.std(math_marks)
print(std_math_marks)


95.0
45.0
73.15
73.5
13.788672887555204
