In [2]:
import numpy as np

a1 = np.array([1,2,3,4])
a2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(a1)
print()
print(a2)

[1 2 3 4]

[[1 2 3 4]
 [5 6 7 8]]


## indexing

In [8]:
print(a1[1])

a1[3] = 100
print(a1[3])
print()

print(a2[0][2])
a2[0][2] = 355
print(a2[0][2])

2
100

3
355


## slicing

In [ ]:
# 1d - arr[start:end:step]
ar = a1[1:4]
print(ar)

[  2   3 100]


In [ ]:
# 2d - arr[row_start: row_end :step, col_start: col_end :step]
print(a2)
print()

# getting a row
row_0 = a2[0:1,]
row_1= a2[1:,]

print(row_0)
print()
print(row_1)

# getting a col
col_0 = a2[::, 0:1]
col_1= a2[::, 1:1]

print(col_0)
print()
print(col_1)
print()

# getting a portion
x = a2[0:2, 0:2]
print(x)
print()
# same
x = a2[::, 0:2]
print(x)
print()

# col 1 full
x = a2[:, 1]
print(x)



[[  1   2 355   4]
 [  5   6   7   8]]

[[  1   2 355   4]]

[[5 6 7 8]]
[[1]
 [5]]

[]

[[1 2]
 [5 6]]

[[1 2]
 [5 6]]

[2 6]
