In [ ]:
import numpy as np

#  sample 10, feature 5
a = np.random.randint(1, 100, size = (10, 5))

#  col -> feature
#  row -> sample
# Q:
#  10 r convert to 5 r
#  5 r convert to 10 r
# -> shape change
#  
b = a.reshape(5,10)

#  5 r, 10 c so value = 5*10 = 50
# Q: convert to 3 * 5, means 3*5=15 value so invalid
#  25 * 2 = 50 possible

# valid given r*c == wanted r*c

In [6]:
#  2d
print(b)
b.shape
b.ndim



[[34  9 65 89 23  4 37 61 33 46]
 [91 11 20 66 73 96 65  7 96 56]
 [57 61 31 26 91 83 24 73 72 36]
 [11 32 70 97 18 38 71 28 88 90]
 [17 65  5 20 55 50 53 77 84 75]]


2

In [ ]:
# 1d  te convert
#  row wise combine
flatten = b.flatten()
flatten.ndim
print(flatten.ndim)
print(flatten)

1
[34  9 65 89 23  4 37 61 33 46 91 11 20 66 73 96 65  7 96 56 57 61 31 26
 91 83 24 73 72 36 11 32 70 97 18 38 71 28 88 90 17 65  5 20 55 50 53 77
 84 75]


In [9]:
# 1d  te convert
#  col wise combine

flatten = b.flatten()
flatten.ndim

col_wise_flattening = np.ravel(b, order= 'F')

print(col_wise_flattening)

[34 91 57 11 17  9 11 61 32 65 65 20 31 70  5 89 66 26 97 20 23 73 91 18
 55  4 96 83 38 50 37 65 24 71 53 61  7 73 28 77 33 96 72 88 84 46 56 36
 90 75]


In [10]:
# 1d  te convert
#  row wise combine

flatten = b.flatten()
flatten.ndim

row_wise_flattening = np.ravel(b, order= 'C')

print(col_wise_flattening)

[34 91 57 11 17  9 11 61 32 65 65 20 31 70  5 89 66 26 97 20 23 73 91 18
 55  4 96 83 38 50 37 65 24 71 53 61  7 73 28 77 33 96 72 88 84 46 56 36
 90 75]


In [15]:
a = np.random.randint(1, 10, size=(2,3))
b = np.random.randint(20, 30, size=(2,3))
print(a)
print(b)

[[5 2 2]
 [1 5 1]]
[[28 29 23]
 [23 28 27]]


concatenate
---
axis = 0 -> if row wise con -> -> col same must

---
axis = 1 -> if col wise con -> -> row same must

In [ ]:
con_row = np.concatenate((a,b), axis=0)  # axis=0 -> row wise -> col same must
print(con_row)

con_col = np.concatenate((a,b), axis=1)  # axis=1 -> col wise -> row same must
print(con_col)

[[ 5  2  2]
 [ 1  5  1]
 [28 29 23]
 [23 28 27]]
[[ 5  2  2 28 29 23]
 [ 1  5  1 23 28 27]]


In [ ]:
#  error

x = np.random.randint(1,5, size=(2,3))
y = np.random.randint(1,5, size=(1,3))

r_c = np.concatenate((x,y), axis=0) # possible
r_c = np.concatenate((x,y), axis=1) #impossible

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Transpose

In [21]:
# Math_eng = [[10,20,30,40],  [30,40,50,60]]

# want to make feature of those two sub marks -> means 2 col
# 10  30
# 20  40
# 30  50
# 40  60

Math_eng = np.array([
    [10,20,30,40],
    [30,40,50,60]
])

transpose = Math_eng.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]
 [40 60]]


In [25]:
# 100 data -> split
# ->model train 60
# ->test 40

a = np.random.randint(1, 10, size=(10,))

splitted_array = np.array_split(a,3)
print(splitted_array)

#  split -> equal division
a = np.random.randint(1, 10, size=(9,))
splitted_array = np.split(a,3)
print(splitted_array)

[array([2, 3, 7, 6], dtype=int32), array([3, 7, 8], dtype=int32), array([7, 5, 6], dtype=int32)]
[array([9, 3, 6], dtype=int32), array([5, 5, 7], dtype=int32), array([8, 7, 6], dtype=int32)]


# ndarray Arithmetic Operators

In [28]:
# x = [10, 20, 30, 40]
# y = [2, 3, 4, 5]

# # loop slow 
# #  so

# add = x+y
# print(add)
# [10, 20, 30, 40, 2, 3, 4, 5]

#  so for proper sum convert it in ndarray

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x+y
print(add)
# [12 23 34 45] perfect

print(x*y," ",  x/y," ", x%y," ", x//y)


[12 23 34 45]
[ 20  60 120 200]   [5.         6.66666667 7.5        8.        ]   [0 2 2 0]   [5 6 7 8]


# Mathematical function

In [30]:
#  trigonmetry
#  sin,  cos,  tan  takes values in radiaan

print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

#  degree to radian
#  degree : 0 * pai/180  -> r
print(np.deg2rad(x))
#  radian to degree
#  radian : r * 180/pai  -> d
print(np.rad2deg(x)) 

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
[0.17453293 0.34906585 0.52359878 0.6981317 ]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


# # log

In [ ]:


base_10_log_val = np.log10(x)
print(base_10_log_val)

# 100 k 10 diye koybar vag kora jabe?
# 100/10 = 2
print(np.log10(100))

# 100/2 = 6
print(np.log2(100))

# 8/2 = 3
print(np.log2(8))


[1.         1.30103    1.47712125 1.60205999]
2.0
6.643856189774724
3.0


# sqrt

In [36]:
x = np.array([10, 8, 16, 100])
print(np.sqrt(x))

[ 3.16227766  2.82842712  4.         10.        ]


In [40]:
print(np.sum(x))  # total array sum

# prefix sum
print(np.cumulative_sum(x))



134
[ 10  18  34 134]
