nd data type

In [6]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.dtype)

a=np.array([1.2, 3.4, 5.6])
# float64, always try to use it, it gives max precision
print(a.dtype)  


# upcasted to float

a=np.array([1, 3, 5.6])
print(a.dtype) #float64

# int   float
# 1   ->  1.0   possible
# 1.0 -> 1.0    possible
# 1   <-   1.0  not possible

# upcasted to string
a = np.array([1,3,'naba',1.2])
print(a.dtype)   # <U32 ,string



int64
float64
float64
<U32


### selecting a data type for an array

In [8]:
# change data type
a = np.array([1,2,3], dtype=np.int8)
print(a.dtype)
print(a)

int8
[1 2 3]


In [16]:
a = np.array([1,2,300], dtype=np.int16)
print(a.dtype)
print(a)


a = np.array([1,2,300], dtype=np.float64)
print(a.astype(np.int32))
print(a)

int16
[  1   2 300]
[  1   2 300]
[  1.   2. 300.]


In [15]:
a = np.array([1,2,300])
print(a.dtype)
print(a)

print(a.astype(np.int16))
 

int64
[  1   2 300]
[  1   2 300]


## Error

In [12]:
# OverflowError: Python integer 300 out of bounds for int8
a = np.array([1,2,300], dtype=np.int8)
print(a.dtype)
print(a)

# ValueError: invalid literal for int() with base 10: 'naba'
# as string k int e convert korte cacchi
a = np.array([1,2,'naba'], dtype=np.int16)
print(a.dtype)
print(a)

OverflowError: Python integer 300 out of bounds for int8