 ndarray creation from range -> we can dicide which value will be set in which position ,but random give random value at random position by probability

In [6]:
import numpy as np
# a = np.arange(start, end, step)  # same to range func 
a = np.arange(1, 10, 1)  # 

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)


# matrix create
# (1, 10, 1) -> 9 values so 3*3
a = np.arange(1, 10, 1).reshape(3,3)   

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)



[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


In [ ]:
"""
np.linspace(start, end(included), koita)

range 6
pick 6 point, evenly divide kore pick korbe
1---2---3---4--5---6---7
0                  6

range 6
pick 10 point, evenly divide kore pick korbe
1---2---3---4--5---6---7
0                  6

"""

In [9]:
a = np.linspace(1, 10, 10)   

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

print()

a = np.linspace(1, 10, 15)   

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
(10,)
1

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1


np.logspace(start, end(included), koita)

In [ ]:

a = np.logspace(0, 4, 5)   
print(a)

# 1.e+00 1.e+01 1.e+02 1.e+03 1.e+04
# 10^0 to 10^4


print()

a = np.logspace(0, 4, 6)   
print(a)


print()

a = np.logspace(0, 4, 6, base=2)   
print(a)

# 2^0 ->0.8 ->1.6 ->2.4  -> 3.2 4


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]

[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
