In [ ]:
# ndarray creation from existing data

# existing data -> list, set, dicc



## From list

In [ ]:
import numpy as np

lst = [10,20,30,40, 40.5]

a = np.array(lst)
print(a)
print(type(a))
print(a.dtype)


a = np.array(lst, dtype=np.int32)
print(a)
print(type(a))
print(a.dtype)

# mixed list e string eer saathe aabr list add koraa jabe an
mixed_lst = [10,True,'Hello', 10.5]
mixed_lst = np.array(mixed_lst)
print(mixed_lst)
print(type(mixed_lst))
print(mixed_lst.dtype)  #<U32, string


matrix = [
    [1,2,3],
    [5,6,7]
]

a= np.array(matrix)
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64
[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
int64
(2, 3)


## From tuple

In [ ]:
tup = (1,2,3,4)

a = np.array(tup)
a= np.array(tup)

# a= np.array(tup, dtype=np.int32)
a = a.astype(np.int16)

print(a)
print(type(a))
print(a.dtype)
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
int16
(4,)


## from set

In [ ]:
st = {1,2,3,4}

a = np.array(st)
a= np.array(st)

print(a)
print(type(a))
print(a.dtype)
print(a.shape)

# error
# a= np.array(st, dtype=np.int32)
# a = a.astype(np.int16)

#  {1, 2, 3, 4}
# <class 'numpy.ndarray'>
# object
# ()
# 1 element hisebe niche


# so convert to list

st = {1,2,3,4}

a = np.array(list(st))
a= np.array(list(st))

print(a)
print(type(a))
print(a.dtype)
print(a.shape)

{1, 2, 3, 4}
<class 'numpy.ndarray'>
object
()
[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)


## from dic

In [ ]:
dic = {'a' : 10, 'b' :2}

print(dic.keys())
print(dic.values())
print(dic.items())

a = np.array(dic)
a= np.array(dic)


print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)
# error same as set 
# a= np.array(tup, dtype=np.int32)
# a = a.astype(np.int16)


# keys to ndarraay
a = np.array(list(dic.keys()))
print(a)

# values to ndarraay
a = np.array(list(dic.values()))
print(a)

a= np.array(list(dic.values()))
print(a)
a = a.astype(np.int32)
print(a)


# items to ndarray
a = np.array(list(dic.items()))
print(a)
print(type(a))
print(a.dtype)   #<U21
print(a.shape)
print(a.ndim)

dict_keys(['a', 'b'])
dict_values([10, 2])
dict_items([('a', 10), ('b', 2)])
{'a': 10, 'b': 2}
<class 'numpy.ndarray'>
object
()
0
['a' 'b']
[10  2]
[10  2]
[10  2]
[['a' '10']
 ['b' '2']]
<class 'numpy.ndarray'>
<U21
(2, 2)
2
