In [ ]:
"""
np.full((r, c), v)
    •Creates an array of shape (r, c)
    •filled with the value v
    
np.full((r, c), np.inf)
    •Creates an array of shape (r, c)
    •filled with the value infinity
    
np.empty_like(arr)
   • Creates a new array with same shape and type as arr
   • Values are uninitialized (random garbage)
   • Values are uninitialized (one -> 1)
   • Values are uninitialized (zero -> 0)
     
np.ones_like(arr)
    • Creates a new array with same shape and type as arr
    • Filled with ones/empty/zeros
    
np.zeros((r, c), dtype)
    • Creates an array of shape (r, c) filled with zeros
    • Uses specified data type (dtype)
    
    
    
"""

nd array from scratch

In [ ]:
import numpy as np

# a = np.full((row,col))
# a = np.full((row,col), val)
# a = np.empty_like(arr_3d)
# a = np.zeros((4,3), dtype=np.int8) 
# a = np.ones_like(arr_3d)

# by defaault value set as 0

# a = np.zeros((1,3))   # 1 row, 3 col
# a = np.zeros((2,3))   # 2 row, 3 col

a = np.zeros((2,3), dtype=np.int8) 
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2


In [8]:
arr_3d = np.array([
    # colomns 4
    [   
    # 1st floor
      [1,2,3,4], #row1
      [5,6,7,8] #row2
    ],
    # 2nd floor
    [
      [1,2,3,4], #row1
      [5,6,7,8] #row2
    ]
    
])

##############  np zero
a = np.zeros((4,3), dtype=np.int8) 
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

# arr_3d er same ,set values to 0
a = np.zeros_like(arr_3d)
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


In [11]:
############ np one

a = np.ones((3,4,3), dtype=np.int8)  # 3d
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)
# arr_3d er same ,set values to 1
a = np.ones_like(arr_3d)
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


In [19]:
############ np empty

# random values show
a = np.empty((4,3), dtype=np.int8)  # 3d/2d can create by this
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)
# arr_3d er same ,set values to 1
a = np.empty_like(arr_3d)
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 4)
3


# per value fill up with any value

In [23]:
# per value fill up with infinity
a = np.full((4,3), np.inf)  # 3d/2d can create by this
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2


In [ ]:
# per value fill up with 10
a = np.full((4,3), 10)  # 3d/2d can create by this
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)


# per value fill up with True
a = np.full((4,3), True)  # 3d/2d can create by this
print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
bool
(4, 3)
2
