In [3]:
import numpy as np
a = np.random.rand(2,3)  # 0 -> 1, floting

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[0.32088947 0.58277152 0.46160095]
 [0.11661821 0.85177133 0.61432266]]
<class 'numpy.ndarray'>
float64
(2, 3)
2


In [4]:
# a = np.random.randint(start_range, end_range, shape) 
a = np.random.randint(1, 10, (2,3))  # 2d

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)


a = np.random.randint(1, 10, (2,))  # 1d

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[4 5 1]
 [3 7 5]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
[8 2]
<class 'numpy.ndarray'>
int32
(2,)
1


In [5]:
#  floating
# a = np.random.uniform(start_range, end_range, shape) 
a = np.random.uniform(50, 100, (3,4))  # 2d

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)


a = np.random.randint(1, 10, (2,))  # 1d

print(a)
print(type(a))
print(a.dtype)   
print(a.shape)
print(a.ndim)

[[62.46590552 85.92210052 64.13318129 93.69001145]
 [54.57230185 85.87166928 97.101022   56.71189037]
 [65.55849777 56.12596016 99.44151391 72.70779992]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
[7 4]
<class 'numpy.ndarray'>
int32
(2,)
1
